[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.2.6"
env_logger = "0.11.2"
libc = "0.2.153"
log = "0.4.20"
sdl2 = "0.36.0"
