[package]
name = "oxide"
authors = ["SNIAPA"]
version = "0.5.0"
edition = "2021"
repository = "https://github.com/SNIAPA/oxide"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
gl = "0.14.0"
imgui-sdl2-support = "0.11.0"
imgui-sys = "0.11.0"
libc = "0.2.153"
sdl2-sys = {version = "^0.34.5", features = ["ttf"]}

