[package]
name = "oxide"
authors = ["SNIAPA"]
version = "0.5.0"
edition = "2021"
homepage = "https://github.com/SNIAPA/oxide"
repository = "https://github.com/SNIAPA/oxide"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.153"
sdl2-sys = "0.36.0"
