[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.2.6"
libc = "0.2.153"

[build]
target = "i686-unknown-linux-gnu"

