#!/bin/python3.11
import re
import subprocess

with open("Cargo.toml",mode="r+") as f:
    
    old_file = f.read()
    matches = re.search(r"(.*version = \"[0-9]*\.[0-9]*\.)([0-9]*)(\".*)",old_file,re.S)
    if matches:
        g = matches.groups()
        print(f'version bumped to {int(g[1]) + 1}')
        f.write("".join([g[0],str(int(g[1]) + 1),g[2]]))
