use crate::*;

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ViewSetup {
    pub x: c_int,
    pub unscaled_x: c_int,
    pub y: c_int,
    pub unscaled_y: c_int,
    pub width: c_int,
    pub unscaled_width: c_int,
    pub height: c_int,
    pub stereo_eye: c_int,
    pub unscaled_height: c_int,
    pub ortho: bool,
    pub ortho_left: c_float,
    pub ortho_top: c_float,
    pub ortho_right: c_float,
    pub ortho_bottom: c_float,
    pub fov: c_float,
    pub fov_viewmodel: c_float,
    pub origin: Vector3,
    pub angles: Angles,
    pub z_near: c_float,
    pub z_far: c_float,
    pub z_near_viewmodel: c_float,
    pub z_far_viewmodel: c_float,
    pub render_to_subrect_if_larger_screen: bool,
    pub aspect_ratio: c_float,
    pub off_center: bool,
    pub off_center_top: c_float,
    pub off_center_bottom: c_float,
    pub off_center_left: c_float,
    pub off_center_right: c_float,
    pub do_bloom_and_tone_mapping: bool,
    pub cache_full_scene_state: bool,
    pub view_to_projection_override: bool,
    pub view_to_projection: VMatrix,
}
